### ISSUE TITLE
Blocking stuff EVERYWHERE

### ISSUE THREAD

**Issue by laggycomputer** [EthanHicks1/PaladinsAssistantBot#2]
I would like to point out that `discord.py` is an asynchronous library, and anything blocking (synchronous) must be placed inside an executor to avoid delays. Your HTTP lib, Pyrez, uses `requests`, which is blocking. I can see that these blocking functions are being consolidated into other blocking functions, which are being used inside commands. I'd recommend using executors to prevent blocking up of threads.

**Comment by EthanHicks1** [comment]
Ok. I will look into this. I don't have experience with blocking in Python but have dealt with it some in C/C++.

**Comment by EthanHicks1** [comment]
Thanks for the feedback. I was able to use executors like whats seen below in the necessary functions to prevent blocking.
```python
executor = ThreadPoolExecutor(max_workers=1)
loop = asyncio.get_event_loop() 
result = await loop.run_in_executor(executor, function_name, user_input)
```
